from snakemake.utils import min_version


# Configuration
configfile: "config/config.yaml"


# Settings
min_version("7.32.4")


# Define modules
module gencode:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/gencode/main/workflow/Snakefile"
    config:
        config


module genome:
    snakefile:
        "https://raw.githubusercontent.com/ctubbs750/genome/main/workflow/Snakefile"
    config:
        config


module install:
    snakefile:
        "rules/install.smk"
    config:
        config["UNIBIND-ACTIVITY"]


module active:
    snakefile:
        "rules/active.smk"
    config:
        config["UNIBIND-ACTIVITY"]





# Import modules
#use rule * from gencode as gencode_*


use rule * from install as install_*


use rule * from active as active_*




###
# Rules
###


rule all:
    message:
        """
        DEPLOYING UNIBIND-ACTIVITY...
        """
    input:
        rules.install_all.input,
        rules.active_all.input,
